# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project05 Calculator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Project05 Calculator
  pod 'SnapKit'
end
